var RoleData = {

    ROLE_HARVESTER:'harvester',
    ROLE_UPGRADER: 'upgrader',
    ROLE_BUILDER:'builder',
    ROLE_REPAIRER: 'repairer',
    ROLE_LONG_HARVESTER: 'longharvester',
    ROLE_SCOUT: 'scout',
    ROLE_WALL_REPAIRER:'wallrepairer',
    ROLE_TRANSPORTER: 'transporter',
    ROLE_CONTROLLER_TRANSPORTER: 'controllertransporter',

    ROLE_HARVESTER_PRIORITY: 0,
    ROLE_TRANSPORTER_PRIORITY: 1,
    ROLE_UPGRADER_PRIORITY: 1,
    ROLE_CONTROLLER_TRANSPORTER_PRIORITY: 1,
    ROLE_REPIARER_PRIORITY: 2,
    ROLE_WALL_REPAIRER_PRIORITY: 3,
    ROLE_BUILDER_PRIORITY: 4,
    ROLE_LONG_HARVESTER_PRIORITY: 5,
    ROLE_SCOUT_PRIORITY: 6,

}

module.exports = RoleData;